name: Probando cypress y github action
on:
  push:
   branches: 
    - 'main'
jobs:
  cypress-test:
    name: Run on chrome 97
    runs-on: ubuntu-18.04
    container: cypress/browsers:node16.5.0-chrome97-ff96
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cypress and verify
        run: |
          npm ci 
          $(npm bin)/cypress verify
      - name: Run cypress test
        run: npm run test:cy
        continue-on-error: false
        
      - name: Comy test execution videos and screenshots
        run: |
          mkdir public2
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
      
      - name: Merge test reports
        run: npm run combine:report
      
      - name: Generate HTML report
        run: npm run generate:report
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
      
        
        
  
